name: Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: |
        sudo apt-get update -qq
        sudo apt-get install -qq xvfb libgl1-mesa-glx libsdl2-dev mesa-utils

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - run: |
        xvfb-run --auto-servernum glxinfo
        go build -v
        export MESA_GL_VERSION_OVERRIDE=3.3COMPAT & xvfb-run --auto-servernum go test -run TestSDL2 ./app
        export MESA_GL_VERSION_OVERRIDE=3.3COMPAT & xvfb-run --auto-servernum go test -run TestGLFW ./app
