name: Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: |
          sudo apt-get update -qq
          sudo apt-get install -qq xvfb libgl1-mesa-glx libsdl2-dev mesa-utils freeglut3-dev

      - env:
          MESA_GL_VERSION_OVERRIDE: 3.3COMPAT
        run: |
          xvfb-run --auto-servernum glxinfo
          go build -v
          xvfb-run --auto-servernum go test -run TestSDL2 ./app
          xvfb-run --auto-servernum go test -run TestGLFW ./app
          xvfb-run --auto-servernum go test -run TestGlut ./app
