name: build
on:
  push:
    branches:
      - master
env:
  go-version: 1.15
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgl1-mesa-glx libsdl2-dev

      - run: |
          xvfb-run go run main.go
