name: Build (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          release: false
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-mesa
            mingw-w64-x86_64-SDL2

      - name: OpenGL
        env:
          MESA_VERSION: '24.0.7'
        shell: msys2 {0}
        run: |
          wget -q https://github.com/pal1000/mesa-dist-win/releases/download/$MESA_VERSION/mesa3d-$MESA_VERSION-release-msvc.7z
          "/c/Program Files/7-Zip/7z.exe" x mesa3d-$MESA_VERSION-release-msvc.7z -omesa
          echo -e " 1\r\n 9\r\n " >> commands
          ./mesa/systemwidedeploy.cmd < ./commands

      - name: Build
        shell: msys2 {0}
        env:
          MESA_GL_VERSION_OVERRIDE: 3.3COMPAT
        run: |
          go build -v
          go test -run TestSDL2 ./app
          go test -run TestGLFW ./app
