name: Build (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: 'mingw-w64-x86_64-pkg-config mingw-w64-x86_64-mesa mingw-w64-x86_64-SDL2'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        shell: msys2 {0}
        env:
          MESA_GL_VERSION_OVERRIDE: 3.3COMPAT
        run: |
          printenv
          go build -v
          go run main.go
