name: Build (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-mesa
            mingw-w64-x86_64-SDL2

      - name: OpenGL
        shell: msys2 {0}
        run: |
          wget https://github.com/pal1000/mesa-dist-win/releases/download/20.2.1/mesa3d-20.2.1-release-mingw.7z
          "/c/Program Files/7-Zip/7z.exe" x mesa3d-20.2.1-release-mingw.7z -omesa
          echo -e " 2\r\n 8\r\n " >> commands
          ./mesa/systemwidedeploy.cmd < ./commands

      - name: Build
        shell: msys2 {0}
        env:
          MESA_GL_VERSION_OVERRIDE: 3.3COMPAT
        run: |
          go build -v
          go test -run TestSDL2 ./app
          go test -run TestGLFW ./app
